# ============================================================
# Configuration run_migration, generated on Mon Sep 07 21:39:39 CEST 2026, by 539693
# * version jar : str_simulateur-bigData-2026_1.6.10-RELEASE.jar
# * Id Project : 2026Q2
# * Id Portefeuille : 3744
# * Id Parametre : Input_STE_ifrs926Q2_SICR3_v2
# * Id Projection : 10551
# ============================================================

projection.periods=
parameter.asOfDateQuarter=2026Q2
scenarios=Adverse,Central,Optimistic,Extreme,Secto
sicr3_scenarios_switch=Adverse,Central,Optimistic,Extreme,Secto
run.launch.type=TWIST
run.realUserId=539693
run.history.tablename=RUN_HISTORY
run.simulation.category=STAPO

#=============================
#External Referentials
#=============================

input.path.referentials.n013=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielExterne/external_referentials_newJar/3405/n013_Template.csv
input.path.referentials.n046_ifrs9=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielExterne/external_referentials_newJar/3405/n046_ifrs9_Template.csv
input.path.referentials.s074=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielExterne/external_referentials_newJar/3405/s074_Template.csv
input.path.referentials.s075=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielExterne/external_referentials_newJar/3405/s075_Template.csv
input.path.referentials.s256=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielExterne/external_referentials_newJar/3405/s256_Template.csv
input.path.crr3_ltv_err=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielExterne/external_referentials_newJar/3405/crr3_ltv_err_Template.csv
input.path.referentials.n015=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielExterne/external_referentials_newJar/3405/n015_Template.csv
input.path.referentials.s067_ifrs9=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielExterne/external_referentials_newJar/3405/s067_ifrs9_Template.csv
input.path.referentials.s279=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielExterne/external_referentials_newJar/3405/s279_Template.csv

#=============================
#Internal Referentials
#=============================

input.path.referentials.internal=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/Import_Ref_internes_newJar.xlsx
input.path.referentials.internal.InternalRefFlexLGDLargeCorp=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/InternalRefMappingCodePrdLgd.csv
input.path.referentials.internal.internalRefPtfR2ReduitPME=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/InternalRefPtfR2ReduitPME_vCTM.xlsx
input.path.referentials.ref_addon_bank=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/refAddonBank.xlsx
input.path.referentials.pd_variation=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/REF_BACKSTOP_PD_SICR3_25Q4_v0.csv
input.path.parameters.app_rate=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/mpp_rates_ref.xlsx
input.path.referentials.hrc_pd=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/REF_HRC_PD_25Q4_v0.csv
input.path.referential.pf_perimeter=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/REF_PF_PERIMETER_25Q4_v0.xlsx
input.path.referentials.matrix-mapping=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/mappingRatingIndex.csv
input.lgd_forward_looking.hlc_referential.path=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/REF_HLC_LGD_ifrs926Q1_v0.xlsx
input.path.crr3_risk_parameters_rules=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/crr3_risk_parameters_rules_Template.xlsx
input.path.crr3_ref_ctm_fac_optima=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/crr3_ref_ctm_fac_optima_Template.csv
input.path.crr3_ltv_rw=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/crr3_ltv_RW_Template.csv
input.path.crr3_ref_ctm_fac_rw=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/crr3_ref_ctm_fac_rw_Template.csv
input.path.referentials.sicr3_res_mat=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/REF_SICR3_RES_MAT_25Q4_v2.csv
input.path.referentials.irba.bank=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/IRBA_ADDON_BANK_Template.csv
input.path.referentials.s137=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/s137_Template.csv
input.path.referentials.nme=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/NME.csv
input.path.referentials.ref_invest_pro=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/REF_INVEST_PRO.csv
input.path.referentials.ref_flg_lg=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/REF_FLG_LG.csv
input.path.referentials.ead_fwl.ref_cib_region_eb=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/REF_CIB_REGION_GB.csv
input.path.referentials.ead_fwl.ref_cib_eb_flg=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/ReferentielInterne/RefInternes2026Q1_v0_newJar_v0/3409/REF_CIB_GB_FLG_25Q4_v1_newJar.csv

#FLAIR extension
activePerfectForesight=false
parameter.activate_ead_amortissement=false
parameter.active_flair_extension=false
parameter.use_chr_at_origination=true
parameter.active.hrc=true
parameter.include.vr-risque=false
parameter.listSegmentationMacCorpSec=MS,ER
parameter.listSegmentationMacCorpLarge=AB,AP,GE,GR,II
parameter.listNoncrashPerimeter=MTGE,NON_S,MTGE_S
parameter.facteur_reducteur=0.7619
parameter.confidenceLevel=0.999
parameter.addon=1.05
parameter.facteur_multiplication=1.25
parameter.scalingFactor=1.06
parameter.amount.type=kAG
parameter.facteur.multiplication.irba=0.188
parameter.indicateur_LGDREG=0.125
parameter.zttc=0
parameter.zreg=-2.32634787
parameter.indicator=0.125
parameter.listRiskCtprMethod=CTPY - CEP,CTPY - CCR
parameter.sicr.default.idealized.structure.term=MASTERSCALE
parameter.default.rating_scale=DEFAULT_IFRS9

#Enable migration
parameter.enable_migration=false
parameter.enable_gross_provision_ead=true
parameter.use_lgd_forward_looking=true
parameter.lgd_forward_looking.use_id_chp_field=true
input.lgd_forward_looking.epsilon_for_hlc=0.0001

#Run type
run.type=Normal

#ADD ON IRBA
parameter.pd_add_on_factor=1.15
parameter.lgd_add_on_factor=1.17
parameter.pd_models_add_on_list=PSMPEA01
parameter.lgd_models_add_on_list=LSCOFB40
parameter.pd_models_add_on_bank_list=PNBOM

#AE
input.path.expert_judgment_projection=/Projects/STCreditRisk_STE/Projection_Production/Output_Cluster/IHM/10551/migration_matrix_AE.csv
parameter.enable_expert_judgment=false
parameter.maxAmount_expertJudgement=2000000.0
parameter.expertJudgementPTFSTT=

#Monte Carlo
monte.carlo.quantiles=0.1,0.5,0.9

#Staging
stage.floor.s2.activation=true

#SICR
parameter.sicr_activation_flag=3
parameter.restagingT0_activation=0
parameter.sicr.pd_pit_ifrs9_weighted_backstop=false
parameter.sicr.default_origination_date_historic=2017Q3
parameter.sicr.default_origination_date_historic_mapping=2018Q1
parameter.sicr.term_structure_historic_floor=0.0001
parameter.sicr.ratio_secto_baseline_floor=0.5
parameter.sicr.ratio_secto_baseline_cap=100
parameter.sicr3_pu_variation=0.04
parameter.sicr3.fallback-staging.matrix=
parameter.active.cd_niv_risk_chr_origin=true
parameter.active.include_sicr_fl8_origin=true

#Denotching
parameter.supported.rating.scales.origin=RB_LG,RB_AF,RB_BNL_RETAIL,RB_FL_FUNDS,RB_FL_BANKS,RB_FL_INSU
parameter.chr.denotching.rating.scales=BCE_RETAIL
input.path.parameters.mappingSST.denotching_micro=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/DENOTCH_INDIV_Template.csv

#Add on EBA
parameter.addon_riskctpr_factor=1.05
parameter.addon_riskctpr_list=CTPY - CCR
parameter.enable_ccr2_application=false

#NPL
parameter.active_npl=false
parameter.activateNPL_output=false

#cor_old
parameter.date_cor_old=null
parameter.use_approbation_type_rwa=true

#Facteur ajustement
use_facteur_ajustement_from_scenario=

#IFRS9
parameter.watchlist=true
parameter.ptf_aging=0
parameter.climate_ifrs9_activation_flag=false
parameter.activate_dpd_fbe_contagion=false
parameter.risk_approach_activate=false

#CRR3
parameter.use_crr3=false
parameter.active_dbe_diligence=null
parameter.activate_el_quaterly=true
parameter.use_bale_iv_optima_substitution_flag=false
parameter.use_stressed_nl_from_ltv_perimeter=false

#RTS_36
parameter.active_RTS_36_AddOn=true

#FAIL_WITH_EXCEPTION
parameter.fail_with_exception=false

#CAP_LGD
parameter.active_cap_lgd=false

#Parameter
input.path.parameters.denotching=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/denotching_Template.xlsx
input.path.referentials.irba=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/importrefmoteurIRBA_Template.xlsx
input.path.prj.mapping_migration.matrix=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/mapping_idealisation_migrationmatrix_26Q2.csv
input.path.parameters.mappingSST=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/mapping_STT_SICR_ifrs9_26Q2_v2.xlsx
input.path.referential.pd-to-lgd=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/chr_pd_empty_NEW.xlsx
input.path.parameters.choc_pd=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/matriceSstage_CICR25Q4_v0.xlsx
input.path.referentials.stageMatrix=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/ratingscales_26Q2_v0.csv
input.path.prj.rating.scale.idealized.matrix=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/ratingtoedf_26Q2_v0.csv
input.path.edf.note.contrepartie=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/stressLGD_IFRS9_26Q1_v0_newJar.xlsx
input.path.parameters.stressLgd=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/ratingtoedf_26Q2_v0.csv
input.path.edf.note.contrepartie=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/stressLGD_IFRS9_26Q1_v0_newJar.xlsx
input.path.parameters.stressLgd=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/ratingtoedf_26Q2_v0.csv
input.path.chr_risk_level_origin_historic.path=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/ref_BCEF_CHR_Histo_STE_26Q2_v0.csv
input.path.term_structure_mapping.path=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/mapping_sicr3_approach_26Q2_v0.csv
input.path.referentials.irba.ste=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/CRR_PARAM_ADD_ON_STE_17092024.csv
input.path.parameters.switching.rts.36=
input.path.referentials.mapping_stc_ead=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/75_EAD_FWD_26Q2_v1.csv
input.path.referentials.ts_ead_fwd=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/climate_denotching_trajectory_Template.csv
input.path.parameters.climate_denotching.trajectory=/Projects/STCreditRisk_STE/STRESSTEST/Simulateur/Parameter/Input_STE_ifrs926Q2_SICR3_v2/3764/climate_denotching_trajectory_Template.csv
input.path.parameters.flair=

#projection
input.path.prj.idealized.matrix=/Projects/STCreditRisk_STE/STRESSTEST/Projection/IdealizedMatricesFile_ifrs9_26Q2_v0.csv
input.path.prj.structure.terme=/Projects/STCreditRisk_STE/Projection_Production/Output_Cluster/IHM/10551/term_structure.csv
input.path.prj.structure.terme.historic=/Projects/STCreditRisk_STE/Projection_Production/Output_Cluster/IHM/10551/term_structure_idealised.csv
input.lgd_forward_looking.P_cure_parameters.path=/Projects/STCreditRisk_STE/Projection_Production/Output_Cluster/IHM/10551/LGDmatrix.csv
input.lgd_forward_looking.mapping_ts_lgd.path=/Projects/STCreditRisk_STE/Projection_Production/Output_Cluster/IHM/10551/MappingTsLgd.csv
input.lgd_forward_looking.lgd_by_quarter.path=/Projects/STCreditRisk_STE/Projection_Production/Output_Cluster/IHM/10551/lgd_term_structure_simulator_format_quarterly.csv
input.lgd_forward_looking.lgd_by_year.path=/Projects/STCreditRisk_STE/Projection_Production/Output_Cluster/IHM/10551/lgd_term_structure_simulator_format_yearly.csv
input.path.projection=/Projects/STCreditRisk_STE/Projection_Production/Output_Cluster/IHM/10551/migration_matrix.csv
input.path.amortization_projection=/Projects/STCreditRisk_STE/Projection_Production/Output_Cluster/IHM/10551/migration_matrix.csv
input.path.projection=/Projects/STCreditRisk_STE/Projection_Production/Output_Cluster/IHM/10551/z_results.csv
input.path.prj.structure.terme.historic.pit=/Projects/STCreditRisk_STE/STRESSTEST/SICRIII/Output/3123/term_structure_histo_fmt.csv
input.path.prj.structure.terme.historic.ttc=/Projects/STCreditRisk_STE/STRESSTEST/SICRIII/Output/3123/term_structure_idealised_histo_fmt.csv
input.path.prj.structure.terme.historic.z=/Projects/STCreditRisk_STE/STRESSTEST/SICRIII/Output/3123/term_structure_z1_histo_fmt.csv
input.path.prj.weight=/Projects/STCreditRisk_STE/STRESSTEST/SICRIII/Output/3123/TS_weights.csv

#OUTPUTS
output.enable.export.facility=true
output.enable.export.facility.measurement=NONE
output.enable.export.facility.measurement.term=false
output.path.run.directory=/Projects/STCreditRisk_STE/Simulateur_Production/Output_Simulateur/
output.externalTable.activeCreation=true
output.externalTable.name=output_%s_%t
output.append.method=OVERWRITE
runId=5bbad7c8-8e7d-4e88-8106-f00ff4345e0b
global.output.table.name=simulation_results_fac_partitioned_full
global.output.database.name=dbsimulateur
global.output.table.metadata=run_metadata
control.enable.hive.final.check=false

# TECHNIQUE & SECURITE
activate.step.execution.timekeeper=false
log.mode=OFF

#Performance
technical.facilities.subdivision.size=500000000

#Portefeuille
input.path.portfolio=/Projects/STCreditRisk_STE/portfolio/starting_point_ifrs9_no_adjust_2026Q2_260624_v1/FACILITY

#Exclusion
input.path.facility.to.exclude=/Projects/STCreditRisk_STE/portfolio/starting_point_ifrs9_no_adjust_2026Q2_260624_v1/exclusion/exclusion_2026Q2_Input_STE_ifrs926Q2_SICR3_v2_5e6c97f9-477c-4f5f-91e6-996316f85d69.csv

#Filtres des outputs
input.path.facility.perimeter.constraints=

#TABLES HIVE
output.path.exportdirFacilityOutput=/Projects/STCreditRisk_STE/Simulateur_Production/Output_Simulateur/facs_%s_%t/STAPO_sp_starting_point_ifrs9_no_adjust_2026Q2_260624_v1_py_10551_pa_Input_STE_ifrs926Q2_SICR3_v2_20260904_%t
output.path.exportdirFacilityMeasurementOutput=/Projects/STCreditRisk_STE/Simulateur_Production/Output_Simulateur/facs_%s_%t/STAPO_sp_starting_point_ifrs9_no_adjust_2026Q2_260624_v1_py_10551_pa_Input_STE_ifrs926Q2_SICR3_v2_20260904_fac_measure_ByTermOutput
output.path.exportdirFacilityMeasurementByTermOutput=/Projects/STCreditRisk_STE/Simulateur_Production/Output_Simulateur/facs_%s_%t/STAPO_sp_starting_point_ifrs9_no_adjust_2026Q2_260624_v1_py_10551_pa_Input_STE_ifrs926Q2_SICR3_v2_20260904_%t
output.externalTable.nameFacilityMeasurementByTermOutput=dbsimulateur.STAPO_sp_starting_point_ifrs9_no_adjust_2026Q2_260624_v1_py_10551_pa_Input_STE_ifrs926Q2_SICR3_v2_20260904_fac_measure_ByTermOutput
output.externalTable.nameFacilityOutput=dbsimulateur.STAPO_sp_starting_point_ifrs9_no_adjust_2026Q2_260624_v1_py_10551_pa_Input_STE_ifrs926Q2_SICR3_v2_20260904_fac
output.externalTable.nameFacilityWeightedOutput=dbsimulateur.STAPO_sp_starting_point_ifrs9_no_adjust_2026Q2_260624_v1_py_10551_pa_Input_STE_ifrs926Q2_SICR3_v2_20260904_fac
output.externalTable.nameFacilityMeasurementOutput=

#No Secto
output.suffix.for_non_secto_table=nosecto
parameter.rows_per_partition=20000
parameter.activateStatistics=false
hive.metastore.sasl.enabled=true
technical.repartition.load=true
technical.orc.compress=ZLIB
technical.enable.termOutsourcing=false

#Output Monte Carlo disabled
output.monte.carlo.enable.export.details=false
output.monte.carlo.enable.export.distribution=false
output.monte.carlo.enable.export.quantiles=false
output.monte.carlo.externalTable.nameDetailsOutput=details%s_%t
output.monte.carlo.externalTable.nameDistributionOutput=distribution_%s_%t
output.monte.carlo.externalTable.nameQuantilesOutput=quantiles_%s_%t
output.monte.carlo.path.exportdirDetailsOutput=/Projects/STCreditRisk_STE/Simulateur_Production/Output_Simulateur/facs_%s_%t/details
output.monte.carlo.path.exportdirDistributionOutput=/Projects/STCreditRisk_STE/Simulateur_Production/Output_Simulateur/facs_%s_%t/distribution
output.monte.carlo.path.exportdirQuantilesOutput=/Projects/STCreditRisk_STE/Simulateur_Production/Output_Simulateur/facs_%s_%t/quantiles

#CTM-CEC
parameter.active.ctm_cec=false

#Residual Maturity
parameter.activate_residual_maturity=true

#EAD
parameter.use_of_ead_forward_looking=true
parameter.use_ead_forward_from_optima=false