#Paramètres globaux
projection.twist.user=539693
projection.run.type=IFRS9
projection.launch.type=TWIST
parameter.asOfDateQuarter=2026Q3
parameter.firstProjectionDate=2027Q3
projection.nbr.proj=3
projection.name=IFRS9_scn26Q3_scenDraft
projection.run.id=9df8cf3a-c2fa-4bfd-9068-aa6587ba84cf
projection.nbr.proj.npl=5
projection.nbr.z=2
projection.history.activate=true
projection.history.table.name=dbprojection.run_history
scenarios=Adverse;Central;Optimistic;Secto;Extreme;
parameter.climate.denotching.optionsqrt=4
#Chemin des inputs
input.path.model=/Projects/STCreditRisk_STE/STRESSTEST/Projection/Model/modelsTemplate_ifrs9_26Q2_v0/modelsTemplate_ifrs9_26Q2_v0.csv
input.path.historicalZ=/Projects/STCreditRisk_STE/STRESSTEST/Projection/Model/modelsTemplate_ifrs9_26Q2_v0/modelsTemplate_ifrs9_26Q2_v0_historicalZ.csv
input.path.historicalDR=/Projects/STCreditRisk_STE/STRESSTEST/Projection/Model/modelsTemplate_ifrs9_26Q2_v0/modelsTemplate_ifrs9_26Q2_v0_historicalDR.csv
input.path.LGDhistoricalCR=/Projects/STCreditRisk_STE/STRESSTEST/Projection/Model/modelsTemplate_ifrs9_26Q2_v0/modelsTemplate_ifrs9_26Q2_v0_historicalCR.csv
input.path.LGDhistoricalLGD=/Projects/STCreditRisk_STE/STRESSTEST/Projection/Model/modelsTemplate_ifrs9_26Q2_v0/modelsTemplate_ifrs9_26Q2_v0_historicalLGD.csv
input.path.LGDmodel=/Projects/STCreditRisk_STE/STRESSTEST/Projection/Model/modelsTemplate_ifrs9_26Q2_v0/modelsTemplate_ifrs9_26Q2_v0_CR.csv
input.path.var.macro.eco=/Projects/STCreditRisk_STE/STRESSTEST/Projection/Scenario/scen_IFRS9_2026Q3draft_mef.csv
input.path.projectedDR=/Projects/STCreditRisk_STE/STRESSTEST/Projection/DrProjected/ProjectedDR_26Q2def_aged26Q3_BDDBindiv_RB_BCEF_ret_v0.csv
input.path.projectedZ=/Projects/STCreditRisk_STE/STRESSTEST/Projection/ZProjected/Z22Q1_BGLCRE_nonsecto_26Q3_v0.csv
input.path.idealized.matrices.ref=/Projects/STCreditRisk_STE/STRESSTEST/Projection/IdealizedMatrices/IdealizedMatricesFile_ifrs9_26Q2_v0/IdealizedMatricesFile_ifrs9_26Q2_v0.csv
input.path.idealized.matrices.comp=/Projects/STCreditRisk_STE/STRESSTEST/Projection/IdealizedMatrices/IdealizedMatricesFile_ifrs9_26Q2_v0/IdealizedMatricesFile_ifrs9_26Q2_v0_Complement.csv
input.path.idealized.matrices.expert.advice=
input.path.migration.matrices.ref=/Projects/STCreditRisk_STE/STRESSTEST/Projection/RefMigrationMatrice/RefMigrationMatriceTemplate_sicr_26Q1.csv
input.path.rating.scales=/Projects/STCreditRisk_STE/STRESSTEST/Projection/RefRatingScales/RefRatingScales_26Q1_v2.csv
input.path.chr=/Projects/STCreditRisk_STE/STRESSTEST/Projection/Hcr/HCRsets_ifrs926Q1_v0.csv
input.path.shift.z.ref=
input.path.substitution.weights=/Projects/STCreditRisk_STE/STRESSTEST/Projection/SubstitutionWeights/Substitution_W_26Q2def_SICR_v0.csv
input.path.rho=
input.path.models_with_sector=/Projects/STCreditRisk_STE/STRESSTEST/Projection/SectoralizedMod/SectoralizedModels_ifrs9_26Q2.csv
input.path.sector=/Projects/STCreditRisk_STE/STRESSTEST/Projection/SectorsRef/SectorsRefTemplate_25Q4_nace2_v0.csv
input.path.LGDprojectedCR=
input.path.LGDmatrix=/Projects/STCreditRisk_STE/STRESSTEST/Projection/LgdMatrix/LGD_MATRIX_26Q1_v0.csv
input.path.LGDmappingTsLGD=/Projects/STCreditRisk_STE/STRESSTEST/Projection/MappingTsLgd/Mapping_TS_LGD_25Q4_v0.csv
input.path.assetfinance.LTVshocks=
input.path.assetfinance.GammaCurves=
input.path.denotching.climate=/Projects/STCreditRisk_STE/STRESSTEST/Projection/ClimateDenotching/DenotchClimatique_moyen_2025Q3_v0_PR_CF_vF_newNace_v3.csv
input.path.denotching.climate.specific=
input.path.model.specific.floor.cap=
input.path.masterscales=/Projects/STCreditRisk_STE/STRESSTEST/Projection/MasterScales/MasterscaleDefaut20240801.csv
#Z conf
lower.bound.z.dichotomy=-7.0
upper.bound.z.dichotomy=7.0
z.dichotomy.precision=1E-15
zbound.adverse.lower=-3.5
zbound.adverse.upper=3.5
zbound.central.lower=-3.5
zbound.central.upper=3.5
zbound.optimistic.lower=-3.5
zbound.optimistic.upper=3.5
zbound.secto.lower=-3.5
zbound.secto.upper=3.5
zbound.extreme.lower=-3.5
zbound.extreme.upper=3.5
#Matrice conf
probability.floor=0.0001
probability.cap=0.9999
lower.bound.matrix.dichotomy=-7.0
upper.bound.matrix.dichotomy=7.0
matrix.dichotomy.precision=1E-15
#Term structure conf
term.structure.method=1
term.structure.horizon.convergence=1
term.structure.pillars=1,2,3,4,5,6,7,8,9,10,15,20,30,50,100
#Avis d'expert date de défaut
parameter.defaultDate=
#Ponderation
parameter.weightCentral=0.5
parameter.weight.floor=0.1
parameter.weight.cap=0.4
parameter.weight.coeff.extreme=0.2
parameter.weight.floor.extreme=0.05
#DR floor conf
dr.floor.type=floor
dr.floor.value=3.0E-4
#Output configuration
output.database.name=dbprojection
output.table.name.projectedDR=projected_DR
output.table.name.projectedDR.detailed=projected_DR_detailed
output.table.name.projectedZ=projected_Z
output.table.name.projectedZ.detailed=projected_Z_detailed
output.table.name.migrationMatrices=migration_matrix
output.table.name.migrationMatrices.detailed=migration_matrix_detailed
output.table.name.termStructures=term_structure
output.table.name.termStructures.detailed=term_structure_detailed
output.table.name.chr=chr
output.table.name.chr.detailed=chr_detailed
output.table.name.scenariiPonderation=scenarii_Ponderation
output.table.name.model_DRZ.exceptions=model_DRZ_exceptions
output.table.name.projections.run=run_projection
output.table.name.model_migration_matrix_npl.exceptions=migration_matrix_npl_exception
output.table.name.migrationMatricesNPL=migration_matrix_npl
output.table.name.termStructuresIdealised.detailed=term_structure_idealised_detailed
output.table.name.chrIdealised.detailed=chr_idealised_detailed
output.filename.projectedZSimulatorFormat=z_results
output.filename.migrationMatrices=migration_matrix
output.filename.matriceTTC=idealised_matrix
output.filename.termStructureSimulatorFormat=term_structure
output.filename.termStructureIdialisedSimulatorFormat=term_structure_idealised
output.parameter.simulator.format=ifrs9,stresstest
output.hdfs.directory=
local.output.directory=
cluster.output.directory=/Projects/STCreditRisk_STE/Projection_Production/Output_Cluster/IHM/10463/
#Output LGD-FWL
output.table.name.model_CR.exceptions=model_CR_exceptions
output.table.name.projectedCR.detailed=projected_CR_detailed
output.table.name.LGDPcure=pcure
output.table.name.LGD.detailed=LGD
output.filename.projectedCRSimulatorFormat=projectedCR
output.filename.LGDPcureSimulatorFormat=pcure
output.filename.LGDSimulatorFormat=LGD
output.filename.LGDmatrix=LGDmatrix
output.filename.LGD.mappingTsLgd=MappingTsLgd
output.filename.LGD.detailed=LGD_Results_file
output.table.name.LGD.termStructures.detailed=lgd_term_structure_detailed
output.filename.LGD.termStructureSimulatorFormat.quarterly=lgd_term_structure_simulator_format_quarterly
output.filename.LGD.termStructureSimulatorFormat.yearly=lgd_term_structure_simulator_format_yearly
output.filename.LGD.assetFinanceLTVshocks=lgd_asset_finance_ltv_shocks
output.filename.LGD.assetFinanceGammaCurves=lgd_asset_finance_curves
#Hive Configuration
hive.metastore.sasl.enabled=true
#Spark Configuration
spark.sql.sources.partitionOverwriteMode=dynamic
#Log Configuration
log.mode=false
#Python Configuration
python.environment=/analytics/python3/bin/python
